Project1/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project1.Models;

namespace Project1.Controllers
{
    public class CategoriesController : Controller
    {
        private Project1Context db = new Project1Context();

        // GET: Categories
        [Route("shop/collections")]
        public ActionResult Index()
        {
            return View(db.Categories.OrderBy(c => c.CategoryName).ToList());
        }

        // GET: Categories/Details/5
        [Route("categories/{id}")]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Where(c => c.Path == id).FirstOrDefault();
            int catID = category.CategoryID;

            ViewBag.numProducts = db.Products.Where(p => p.CategoryID == catID).ToList().Count();
            ViewBag.products = db.Products.Where(p => p.CategoryID == catID).OrderByDescending(p => p.ReleaseDate).Take(4).ToList();

            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create([Bind(Include = "CategoryID,CategoryName,Path")] Category category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    category.Path = category.CategoryName.ToString().ToLower().Replace(" ", "-");
                    db.Categories.Add(category);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateException ex)
                {
                    SqlException innerException = ex.InnerException.InnerException as SqlException;

                    if (innerException != null && innerException.Number == 2627 || innerException.Number == 2601)
                    {
                        ModelState.AddModelError("CategoryName", "The category " + category.CategoryName + " already exists.");
                    }
                }
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        [Authorize]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Where(c => c.Path == id).FirstOrDefault();
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,CategoryName,Path")] Category category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    category.Path = category.CategoryName.ToString().ToLower().Replace(" ", "-");
                    db.Entry(category).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateException ex)
                {
                    SqlException innerException = ex.InnerException.InnerException as SqlException;

                    if (innerException != null && innerException.Number == 2627 || innerException.Number == 2601)
                    {
                        ModelState.AddModelError("CategoryName", "The category " + category.CategoryName + " already exists.");
                    }
                }
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        [Authorize]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Where(c => c.Path == id).FirstOrDefault();
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Category category = db.Categories.Where(c => c.Path == id).FirstOrDefault();
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project1.Models;
using Project1.ViewModels;

namespace Project1.Controllers
{
    public class HomeController : Controller
    {
        private Project1Context db = new Project1Context();

        public ActionResult Index()
        {
            // select the products
            return View(db.Products.OrderByDescending(p => p.ReleaseDate).Take(6).ToList());
        }

        [Route("contact")]
        public ActionResult Contact()
        {
            return View();
        }
    }
}

Project1/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using PagedList;
using Project1.Models;
using Project1.ViewModels;

namespace Project1.Controllers
{
    public class ProductsController : Controller
    {
        private Project1Context db = new Project1Context();

        // GET: Products
        public ActionResult Index(string category, string search, string order, int? size, int? page)
        {
            // instantiate a new view model
            ProductIndexViewModel viewModel = new ProductIndexViewModel();

            // select the products
            var products = db.Products.Include(p => p.Category);

            // perform the search and save the search string to the viewModel
            if (!String.IsNullOrEmpty(search))
            {
                products = products.Where(p => p.ProductName.Contains(search) ||
                p.Description.Contains(search) ||
                p.Category.CategoryName.Contains(search));
                viewModel.search = search;
            }

            // group search results into categories and count how many items in each category
            viewModel.CatsWithCount = from matchingProducts in products
                                      orderby matchingProducts.Category.CategoryName
                                      group matchingProducts by
                                               matchingProducts.Category.CategoryName into
                                      catGroup
                                      select new CategoryWithCount()
                                      {
                                          CategoryName = catGroup.Key,
                                          ProductCount = catGroup.Count()
                                      };

            if (!String.IsNullOrEmpty(category))
            {
                products = products.Where(p => p.Category.Path == category);
                viewModel.category = category;
            }

            // sort the results            
            switch (order)
            {
                case "price":
                    products = products.OrderBy(p => p.Price);
                    break;
                case "price-desc":
                    products = products.OrderByDescending(p => p.Price);
                    break;
                default:
                    products = products.OrderBy(p => p.ProductName);
                    break;
            }

            int currentPage = (page ?? 1);
            viewModel.size = size;
            viewModel.Products = products.ToPagedList(currentPage, size ?? Constants.PageItems);
            viewModel.order = order;
            viewModel.filters = new Dictionary<string, string>
            {
                {"Low to high", "price" },
                {"High to low", "price-desc" }
            };
            return View(viewModel);
        }

        public ActionResult ProductsOnSale(string category, string search, string order, int? size, int? page)
        {
            // instantiate a new view model
            ProductIndexViewModel viewModel = new ProductIndexViewModel();

            // select the products
            var products = db.Products.Include(p => p.Category).Where(p => p.OnSale == true);

            // perform the search and save the search string to the viewModel
            if (!String.IsNullOrEmpty(search))
            {
                products = products.Where(p => p.ProductName.Contains(search) ||
                p.Description.Contains(search) ||
                p.Category.CategoryName.Contains(search));
                viewModel.search = search;
            }

            // group search results into categories and count how many items in each category
            viewModel.CatsWithCount = from matchingProducts in products
                                      orderby matchingProducts.Category.CategoryName
                                      group matchingProducts by
                                               matchingProducts.Category.CategoryName into
                                      catGroup
                                      select new CategoryWithCount()
                                      {
                                          CategoryName = catGroup.Key,
                                          ProductCount = catGroup.Count()
                                      };

            if (!String.IsNullOrEmpty(category))
            {
                products = products.Where(p => p.Category.Path == category);
                viewModel.category = category;
            }

            // sort the results            
            switch (order)
            {
                case "price":
                    products = products.OrderBy(p => p.Price);
                    break;
                case "price-desc":
                    products = products.OrderByDescending(p => p.Price);
                    break;
                default:
                    products = products.OrderByDescending(p => p.SaleEnd);
                    break;
            }

            int currentPage = (page ?? 1);
            viewModel.size = size;
            viewModel.Products = products.ToPagedList(currentPage, size ?? Constants.PageItems);
            viewModel.order = order;
            viewModel.filters = new Dictionary<string, string>
            {
                {"Low to high", "price" },
                {"High to low", "price-desc" }
            };
            return View(viewModel);
        }

        // GET: Products/Details/5
        [Route("shop/product/{id}")]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Where(p => p.Path == id).FirstOrDefault();

            if (product == null)
            {
                return HttpNotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories.OrderBy(c => c.CategoryName), "CategoryID", "CategoryName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https:// go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,Description,Price,ReleaseDate,OnSale,Discount,SaleStart,SaleEnd,Path,CategoryID")] Product product, HttpPostedFileBase Image)
        {
            if (product.OnSale != false)
            {
                if (product.Discount == null)
                {
                    ModelState.AddModelError("Discount", "Please enter the discount amount.");
                }

                if (String.IsNullOrEmpty(Request["Sale"]) || Request["Sale"] == " to ")
                {
                    ModelState.AddModelError("Sale", "Please select the duration of the sale.");
                }
                else
                {
                    try
                    {
                        var date = Request["Sale"];
                        var saleStart = DateTime.Parse(date.Substring(0, date.IndexOf("to")));
                        var saleEnd = DateTime.Parse(date.Substring(date.IndexOf("to") + 3));
                        product.SaleStart = saleStart;
                        product.SaleEnd = saleEnd;
                    }
                    catch (Exception)
                    {
                        ModelState.AddModelError("Sale", "Please select a range of dates.");
                    }
                }
            }

            //check the user has entered a file              
            if (Image != null)
            {
                if (ValidateExtension(Image))
                {
                    if (ValidateFile(Image))
                    {
                        try
                        {
                            SaveFileToDisk(Image);
                            product.Image = Image.FileName;
                        }
                        catch (Exception)
                        {
                            ModelState.AddModelError("Image", "An error occurred saving the image " + Image.FileName + " to disk. Please try again.");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("Image", "The image " + Image.FileName + " must be smaller than 2MB.");
                    }
                }
                else
                {
                    ModelState.AddModelError("Image", "The file must be .png, .jpg, or .jpeg.");
                }

            }
            else
            {
                // if the user has not entered a file           
                ModelState.AddModelError("Image", "Please select an image.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    product.ReleaseDate = DateTime.Now;
                    product.Path = product.ProductName.ToString().ToLower().Replace(" ", "-");
                    db.Products.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateException ex)
                {
                    SqlException innerException = ex.InnerException.InnerException as SqlException;

Project1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title</h2>
<br />

<address>
    Haut&#232; Couture<br />
    Tysons Corner Mall<br />
    1961 Chain Bridge Rd, VA 22102<br />
</address>

<address>
    <strong>Phone:</strong>     <a href="tel:571.201.7894">571.201.7894</a><br />
    <strong>Support:</strong>   <a href="mailto:support@example.com">support@haut&#232;-couture.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:marketing@example.com">marketing@haut&#232;-couture.com</a>
</address>

Project1/Views/Home/Index.cshtml
@model IEnumerable<Project1.Models.Product>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Haut&#232; Couture</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="wrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Hautè Couture", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.RouteLink("Shop", "ProductsIndex")</li>
                        <li>@Html.ActionLink("Shop by Category", "Index", "Categories")</li>
                        <li>@Html.RouteLink("Sales", "ProductsOnSale")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    @using (Html.BeginRouteForm("ProductsIndex", FormMethod.Get, new { @class = "navbar-form navbar-left", @name = "searchbar", @novalidate = "true" }))
                    {
                        <div class="form-group">
                            @Html.TextBox("search", null, new { @type = "search", @required = "true", @placeholder = "Search products...", @title = "Search products" })
                        </div>
                    }
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </nav>
        <main class="container body-content">
            <div class="hero">
                <img src="@(Url.Content(Constants.ImagePath) + "dotted-red-dress.jpg")" alt="Spring Sale, 15%+ off select items" />
                <div class="text-overlay">
                    <h1>Spring Sale</h1>
                    <i>15%+ off select items</i>
                </div>
                <div>
                    <a href="@Url.Action("ProductsOnSale", "Products")" class="b-r">Shop Sales &rsaquo;</a>
                </div>
            </div>
            <div class="row heroes" id="first">
                <h3>Shop the Collection</h3>
                <div class="flex-container">
                    <div>
                        <a href="@Url.Action("Index", "Products", new { category = "women" })">
                            <img src="@(Url.Content(Constants.ImagePath) + "high-fashion-woman.jpg")" alt="Shop women" />
                        </a>
                        <a href="@Url.Action("Index", "Products", new { category = "women" })" class="shop">Shop Women &raquo;</a>
                    </div>
                    <div>
                        <a href="@Url.Action("Index", "Products", new { category = "teens" })">
                            <img src="@(Url.Content(Constants.ImagePath) + "teens.png")" alt="Shop Teens" />
                        </a>
                        <a class="shop" href="@Url.Action("Index", "Products", new { category = "teens" })">Shop Teens &raquo;</a>
                    </div>
                    <div>
                        <a href="@Url.Action("Index", "Products", new { category = "accessories" })">
                            <img src="@(Url.Content(Constants.ImagePath) + "accessories.jpg")" alt="Shop Accessories" />
                        </a>
                        <a class="shop" href="@Url.Action("Index", "Products", new { category = "accessories" })">Shop Accessories &raquo;</a>
                    </div>
                </div>
            </div>
            <div class="row heroes">
                <h3>New In</h3>
                <div id="gallery" class="flex-container">
                    @foreach (var item in Model)
                    {
                        <figure>
                            <a href="@Url.Action("Details", "Products", new { id = item.Path })">
                                @{
                                    if (String.IsNullOrEmpty(item.Image))
                                    {
                                        <img src="@(Url.Content(Constants.ImagePath) + "no-image.png")" alt="Image Not Found">
                                    }
                                    else
                                    {
                                        <img src="@(Url.Content(Constants.ImagePath) + item.Image)">
                                    }
                                }
                            </a>
                            <figcaption>
                                <a href="@Url.Action("Details", "Products", new { id = item.Path })">
                                    @Html.DisplayFor(modelItem => item.ProductName)
                                </a>
                                @if (item.OnSale != false)
                                {
                                    if (item.Discount > 0)
                                    {
                                        var discount = 1 - Convert.ToDecimal(item.Discount) / 100;
                                        var price = Decimal.Round(discount * item.Price, 2);

                                        <p class="discount">
                                            $@price
                                            (@Html.DisplayFor(modelItem => item.Discount) off)
                                            <span>@Html.DisplayFor(modelItem => item.Price)</span>
                                        </p>
                                    }
                                }
                                else
                                {
                                    <p>@Html.DisplayFor(modelItem => item.Price)</p>
                                }
                            </figcaption>
                        </figure>
                    }
                </div>
            </div>
            <div class="row heroes">
                <h3>Receive Exclusive Offers &amp; Updates</h3>
                <form id="subscribe" name="subscribe" method="post" novalidate>
                    <input type="email" name="email" id="email" placeholder="E-mail Address" />
                    <input type="submit" value="Sign Up" />
                    <p id="success"></p>
                </form>
            </div>
        </main>
    </div>
    <footer>
        <hr />
        <p>&copy; 2020 Hautè Couture</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Scripts/js.js"></script>
    <script>
        $("#subscribe").validate({
            rules: {
                email: {
                    required: true,
                    email: true
                }
            },
            messages: {
                email: {
                    required: "Please enter your e-mail address."
                }
            },
            errorPlacement: function (error) {
                if ($("#email-error").length == 0) {
                    error.insertAfter($("[name=subscribe] input[type='submit']"));
                }
            },
        });

        $("#subscribe").submit(function (e) {
            if ($("#email-error").length == 0 || document.getElementById("email-error").style.display == "none") {
                e.preventDefault();
                $("[name='subscribe'] input").prop("readonly", true);
                $("#success").html("Thanks for subscribing to Hautè Couture.");
            }
        });
    </script>
    <noscript>
        <div class="overlay">
            <div class="overlay-content">
                <p>Please enable <a href="https://enablejavascript.co/">JavaScript</a> and reload this page for optimum website functionality.</p>
            </div>
        </div>
    </noscript>
</body>
</html>